version: '3.3'

services:
  # Database Service
  db:
    image: mysql:latest
    container_name: mysql-db2
    environment:
      - MYSQL_ROOT_PASSWORD=gt
    networks:
      - titan-network
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-php-myadmin
    ports:
      - "8082:80"
    restart: always
    networks:
      - titan-network
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: gt

  # gtExchange Spring Boot Application
  gtExchange:
    image: gt-exchange-image
    container_name: gt-exchange-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    restart: always
    networks:
      - titan-network
    depends_on:
      - db
      - cache
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db2:3306/tx?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: gt

  gtExchangeTwo:
    image: gt-exchange-image
    container_name: gt-exchange-app-2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8084"
    restart: always
    networks:
      - titan-network
    depends_on:
      - db
      - cache
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db2:3306/tx?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: gt

  cache:
    image: "redis:alpine"
    container_name: wanda-cache
    hostname: redis
    networks:
      - titan-network
    ports:
      - "6379:6379"

volumes:
  mysql_data:

networks:
  titan-network: